import { TripItem } from '../../types';

export const itemBuilder: Record<string, TripItem> = {
  flight: {
    id: '',
    name: '',
    type: 'flight',
    origin: '',
    destination: '',
    date: '',
    time: '',
    airline: '',
    price: '',
    url: '',
  },
  hotel: {
    id: '',
    type: 'hotel',
    name: '',
    location: '',
    checkIn: '',
    checkOut: '',
    price: '',
    url: '',
  },
  car: {
    id: '',
    name: '',
    type: 'car',
    company: '',
    pickupLocation: '',
    pickupDate: '',
    dropoffLocation: '',
    dropoffDate: '',
    price: '',
    url: '',
  },
  activity: {
    id: '',
    type: 'activity',
    name: '',
    location: '',
    date: '',
    time: '',
    price: '',
    url: '',
  },
  checklist: {
    id: '',
    name: '',
    type: 'checklist',
    item: '',
    completed: false,
  },
};
